// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCveuOTGecdqujrtCzeEXflCyDzUPpRpIc',
    appId: '1:762357524031:web:4395ab492beff47c0ffa8a',
    messagingSenderId: '762357524031',
    projectId: 'fambite-a7686',
    authDomain: 'fambite-a7686.firebaseapp.com',
    databaseURL: 'https://fambite-a7686-default-rtdb.firebaseio.com',
    storageBucket: 'fambite-a7686.firebasestorage.app',
    measurementId: 'G-BLL0EGQYBC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxSj01IZDWt4HN22oACJ_2gxDSoINlT3Q',
    appId: '1:762357524031:android:6786cd54a2decaa90ffa8a',
    messagingSenderId: '762357524031',
    projectId: 'fambite-a7686',
    databaseURL: 'https://fambite-a7686-default-rtdb.firebaseio.com',
    storageBucket: 'fambite-a7686.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjqKr0S6dMrYMEZycIZW3AFiUtou1tXy4',
    appId: '1:762357524031:ios:0783206cb48e00fc0ffa8a',
    messagingSenderId: '762357524031',
    projectId: 'fambite-a7686',
    databaseURL: 'https://fambite-a7686-default-rtdb.firebaseio.com',
    storageBucket: 'fambite-a7686.firebasestorage.app',
    iosBundleId: 'com.example.famBite',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjqKr0S6dMrYMEZycIZW3AFiUtou1tXy4',
    appId: '1:762357524031:ios:0783206cb48e00fc0ffa8a',
    messagingSenderId: '762357524031',
    projectId: 'fambite-a7686',
    databaseURL: 'https://fambite-a7686-default-rtdb.firebaseio.com',
    storageBucket: 'fambite-a7686.firebasestorage.app',
    iosBundleId: 'com.example.famBite',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCveuOTGecdqujrtCzeEXflCyDzUPpRpIc',
    appId: '1:762357524031:web:d959dcfe9ab26a260ffa8a',
    messagingSenderId: '762357524031',
    projectId: 'fambite-a7686',
    authDomain: 'fambite-a7686.firebaseapp.com',
    databaseURL: 'https://fambite-a7686-default-rtdb.firebaseio.com',
    storageBucket: 'fambite-a7686.firebasestorage.app',
    measurementId: 'G-1HNNRC76QL',
  );
}
